FROM node:20-alpine AS build

WORKDIR /usr/src/app

# Install curl for the healthcheck
RUN apk add --no-cache curl

# Copy the required utils from the shared folder
COPY --chown=node:node ./shared/utils/generateGpuDomId.ts /usr/src/app/shared/utils/generateGpuDomId.ts
COPY --chown=node:node ./shared/utils/calculatePerformance.ts /usr/src/app/shared/utils/calculatePerformance.ts

# Install dependencies
COPY --chown=node:node ./client/package*.json ./
RUN npm ci

EXPOSE 5173

USER node

# Change to the bind mounted host project folder
WORKDIR /usr/src/app/client

CMD ["npm", "run", "dev"]
