FROM node:20-alpine AS build

WORKDIR /usr/src/app

# Install curl for the healthcheck
RUN apk add --no-cache curl

# Install dependencies
COPY --chown=node:node ./alternative-client/package*.json ./
RUN npm ci

EXPOSE 5173

USER node

# Change to the bind mounted host project folder
WORKDIR /usr/src/app/alt-client

CMD ["npm", "run", "dev"]
