# Build stage
FROM node:20-alpine AS build

WORKDIR /usr/src/app

COPY ./package*.json .
COPY ./src ./src
COPY ./environment.d.ts .
COPY tsconfig.json .

RUN npm install
RUN npm run tsc

# Production stage
FROM node:20-alpine AS production

WORKDIR /usr/src/app
COPY ./package*.json .
COPY ./dist ./dist
COPY --from=build /usr/src/app/build .

RUN npm ci

EXPOSE 3001

ENV PORT=3001

CMD ["node", "./index.js"]
