# Build stage
FROM node:20-alpine AS build

WORKDIR /usr/src/app/server

COPY ./server/package*.json .
COPY ./server/src ./src
COPY ./server/environment.d.ts .
COPY ./server/tsconfig.json .
COPY ./shared/types/types.ts ../shared/types/types.ts

RUN npm install
RUN npm run tsc

# Production stage
FROM node:20-alpine AS production

WORKDIR /usr/src/app/server

COPY ./server/package*.json .
COPY ./server/dist ./dist
COPY --from=build /usr/src/app/server/build .

RUN npm ci

EXPOSE 3001

ENV PORT=3001

CMD ["node", "./server/src/index.js"]
